name: General tests
on: [pull_request]
jobs:
  compile-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: git submodule update --init --recursive
      - run: yarn
      - run: yarn test
